Feature/pt 223
technologiesforaccessibility/osmintegrator-backend pull request #118
Opened 2022-03-18 10:37 UTC by micdra7

2022-03-21 07:39 UTC, luktar requested changes

2022-03-21 07:39 UTC, luktar commented on OsmIntegrator.Tests/Data/GtfsImports/AddStopTest/Data.txt
> +1584594015,1,Brynów Dworska,,50.231381,18.982615,/rozklady/przystanek/1584594015/,0
Identyfikator powinien być 6-ści cyfrowy jak w innych przystankach ZTM. Może być wymyślony np. 111111.

2022-03-21 07:39 UTC, luktar commented on OsmIntegrator.Tests/Tests/GtfsImports/ImportTestBase.cs
> +    protected const double EXPECTED_LAT_1 = 50.2313803;
Te wartości można wyłączyć do osobnego pliku ponieważ są niezmienne.

2022-03-21 07:39 UTC, luktar commented on OsmIntegrator/Database/Models/CsvObjects/GtfsStop.cs
> +    public int stop_id { get; set; }
Nazwy propertiesów powinny być w formacie upper camel case. Nazwy docelowe można zmieniać za pomocą atrybutów.

2022-03-21 07:39 UTC, luktar commented on OsmIntegrator/Controllers/TileController.cs
> +    UserRoles.EDITOR + "," + UserRoles.SUPERVISOR + "," + UserRoles.ADMIN + "," + UserRoles.COORDINATOR)]
Edytor nie powinien mieć uprawnień do używania tej metody.

2022-03-21 07:39 UTC, luktar commented on OsmIntegrator.Tests/Data/GtfsImports/AddStopTest/Report.txt
> +[PRZYSTANEK-Dodano] Brynów Dworska, Id: 1584594015, Gtfs, Wer: 0
Przystanki ZTM nie posiadają wersji. Pole `Wer: 0` do usunięcia w przypadku tego raportu.

2022-03-21 07:39 UTC, luktar commented on OsmIntegrator.Tests/Tests/GtfsImports/ImportTestBase.cs
> +    protected const double EXPECTED_LAT_1 = 50.2313803;
Oraz są używane w innych testach.

2022-03-21 07:39 UTC, luktar commented on OsmIntegrator.Tests/Tests/GtfsImports/RemoveStopTest.cs
> +      var content = new MultipartFormDataContent();
Nie używamy `var` jeżeli typ nie jest jasno zdefiniowany.

2022-03-21 07:39 UTC, luktar commented on OsmIntegrator.Tests/Tests/GtfsImports/RemoveStopTest.cs
> +      var fileStreamContent = new StreamContent(File.OpenRead($"{TestDataFolder}{nameof(RemoveStopTest)}/Data.txt"));
Nie ma potrzeby używania `var` w takich sytuacjach w C#10.
Wystarczy `StreamContent fileStreamContent = new(File....`.

2022-03-21 07:39 UTC, luktar commented on OsmIntegrator/Controllers/TileController.cs
> +  public async Task<IActionResult> UpdateGtfsStops([FromForm] IFormFile file)
Ta metoda powinna być wydzielona do osobnego kontrollera. W UI będzie dostępna w Panelu Administratora.

2022-03-21 10:20 UTC, micdra7 commented on OsmIntegrator.Tests/Data/GtfsImports/AddStopTest/Data.txt
> +1584594015,1,Brynów Dworska,,50.231381,18.982615,/rozklady/przystanek/1584594015/,0
Poprawione

2022-03-21 10:20 UTC, micdra7 commented on OsmIntegrator.Tests/Tests/GtfsImports/ImportTestBase.cs
> +    protected const double EXPECTED_LAT_1 = 50.2313803;
Poprawione, wszystkie stałe wrzuciłem do klasy ExpectedValues

2022-03-21 10:20 UTC, micdra7 commented on OsmIntegrator/Database/Models/CsvObjects/GtfsStop.cs
> +    public int stop_id { get; set; }
Poprawione

2022-03-21 10:20 UTC, micdra7 commented on OsmIntegrator/Controllers/TileController.cs
> +    UserRoles.EDITOR + "," + UserRoles.SUPERVISOR + "," + UserRoles.ADMIN + "," + UserRoles.COORDINATOR)]
Poprawione

2022-03-21 10:20 UTC, micdra7 commented on OsmIntegrator.Tests/Data/GtfsImports/AddStopTest/Report.txt
> +[PRZYSTANEK-Dodano] Brynów Dworska, Id: 1584594015, Gtfs, Wer: 0
Poprawione

2022-03-21 10:21 UTC, micdra7 commented on OsmIntegrator.Tests/Tests/GtfsImports/RemoveStopTest.cs
> +      var content = new MultipartFormDataContent();
Poprawione

2022-03-21 10:21 UTC, micdra7 commented on OsmIntegrator.Tests/Tests/GtfsImports/RemoveStopTest.cs
> +      var fileStreamContent = new StreamContent(File.OpenRead($"{TestDataFolder}{nameof(RemoveStopTest)}/Data.txt"));
Poprawione

2022-03-21 10:21 UTC, micdra7 commented on OsmIntegrator/Controllers/TileController.cs
> +  public async Task<IActionResult> UpdateGtfsStops([FromForm] IFormFile file)
Poprawione

2022-03-22 21:22 UTC, luktar approved these changes

2022-03-22 21:24 UTC, luktar commented
PR wygląda bardzo dobrze. Nie miałem czasu sprawdzać. Pewnie dopiero zrobię to w piątek.

2022-03-23 07:35 UTC, merged