Feature 157
technologiesforaccessibility/osmintegrator-backend pull request #50
Opened 2021-08-03 14:53 UTC by pdankowski

https://rozwiazaniadlaniewidomych.atlassian.net/browse/PT-157

W `ErrorControler` potrzebujemy atrybutu `Route` zamiast `HttpGet`. To nie jest endpoint widoczny na zewnątrz, nie chcemy pokazywać tego w `swaggerze`. To jest wewnętrzne rozwiązanie do łapania wtyjątków z kontrolerów

2021-08-03 21:03 UTC, luktar requested changes
Zadanie będzie pomyślnie wykonane, jak swagger będzie generował plik json.

2021-08-03 21:03 UTC, luktar commented on OsmIntegrator/Controllers/ErrorController.cs
> +        [Route("/error-local-development")]
Ja to zmieniłem, bo jak jest ustawione "Route" to nie działa swagger. Musimy wymyśleć jakiś kompromis. Może da sie zignorować te dwa endpointy, aby nie były dodawane do swaggera?

2021-08-04 06:14 UTC, luktar commented
Znalazałem takie coś:
https://stackoverflow.com/a/41624105/1816687

2021-08-04 07:17 UTC, pdankowski commented
teraz działa

2021-08-04 13:31 UTC, luktar approved these changes

2021-08-04 14:40 UTC, merged