[WIP] Feature/pt 235
technologiesforaccessibility/osmintegrator-backend pull request #76
Opened 2021-10-20 06:33 UTC by jganczorz-revolve

2021-10-20 18:03 UTC, luktar requested changes
Zastanowiłbym się nad NoteStatus oraz nad tym jak zmigrować dane na starych komentarzy na nową strukturę.

2021-10-20 18:03 UTC, luktar commented on .config/dotnet-tools.json
> +{
Po co to?

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/ApiModels/Conversation.cs
> +    public Guid TileId { get; set; }
API ma wbudowany walidator. Jeżeli chcesz, żeby Ci sprawdzał, czy to pole jest, ono musi być nullable i musi mieć dodany atrybut [Required].

Tutaj Piotr trafił na problem, że jak identyfikatory GUID nie były nullable to się nie walidowały ponieważ .net uzupełniał je GUIDem z samymi zerami.
Warto, żebyś sam na postmanie spróbował wysłać obiekt z brakującym polem i sprawdził, czy dostajesz odpowiedni komunikat.

Komunikaty o niepoprawnej walidacji nie są tłumaczone na Polski.

Więcej o walidacji: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0#validation-attributes

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/ApiModels/MessageInput.cs
> +  public Guid TileId { get; set; }
Wcięcie

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/ApiModels/MessageInput.cs
> +  public Guid TileId { get; set; }
Nullable `?`

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/AutoMapper/ConversationProfile.cs
> +      AllowNullCollections = true;
Co to daje?

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/AutoMapper/MessageProfile.cs
> +        .ForMember(x => x.Username, o => o.MapFrom(x => x.User.UserName))
Super :)

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/Controllers/ConversationController.cs
> +      if (messageInput.ConversationId == null)
Tutaj dodajemy pierwszą konwersację.

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/Controllers/ConversationController.cs
> +          FirstOrDefaultAsync(x => x.Id == Guid.Parse(id));
ok

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/Controllers/ConversationController.cs
> +      ConversationResponse response = new ConversationResponse()
Po co zwracasz wszystkie konwersacje? Myślałem, że konwersacje będziemy zwracać dopiero jak ktoś kliknie w przystanek.

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/Controllers/ConversationController.cs
> +      ConversationResponse response = new ConversationResponse()
Lub pinezkę z raportem.

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/Controllers/ConversationController.cs
> +    [HttpPut("Approve/{id}")]
Wiem, że stosowałem `id` i jest to poprawne, natomiast dzisiaj myślę, że lepiej byłoby stosować nazwę czego to id dotyczy np. `conversationId`.

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/ApiModels/Conversation.cs
> +  public class Conversation
Czy będziemy sprawdzać status konwersacji (`Open/Approve`) poprzez sprawdzenie, czy ostatnia wiadomość ma status `Approve`?

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/ApiModels/Conversation.cs
> +  public class Conversation
Może przydałoby się tutaj dodać też status. Z drugiej strony trzeba będzie nim zarządzać. Pytanie pozostawiam otwarte.

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/Controllers/ConversationController.cs
> +    public async Task<ActionResult> Reject(string id)
W diagramie nie przewidywaliśmy odrzucenia wiadomości. Odrzucenie było stosowane wcześniej dla raportów pinezek, ale uznaliśmy, że nie ma sensu.

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/Controllers/ConversationController.cs
> +    [HttpPut("Approve/{id}")]
Teraz jak bym chciał to pozmieniać, to musiałbym też naprawiać front ;)

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/Controllers/ConversationController.cs
> +    public async Task<ActionResult> Approve([FromBody] MessageInput messageInput)
I to jest poprawna metoda zatwierdzania konwersacji. W takim razie po co nam ta metoda? `[HttpPut("Approve/{id}")]` z linii 156?

2021-10-20 18:03 UTC, luktar commented on OsmIntegrator/Controllers/ConversationController.cs
> +    public async Task<ActionResult> Reject([FromBody] MessageInput messageInput)
Wg. mnie niepotrzebne.
Też statusy są troche mylące ponieważ jest:
`NoteStatus -> Created, Rejected, Approved`, a powinno być
`Active / Inactive`
Może warto dodać osobny status, a w ten `NoteStatus` usunąć po migracji starych komentarzy na nowe.

2021-10-21 13:10 UTC, luktar requested changes

2021-10-21 13:10 UTC, luktar commented on OsmIntegrator/ApiModels/Conversation.cs
> +    public double? Lat { get; set; }
Pola powinny być [Required] jeżeli są wymagane.

2021-10-22 05:07 UTC, jganczorz-revolve commented on .config/dotnet-tools.json
> +{
VSCode wymaga dodatkowych narzędzi, żeby tworzyć migracje

2021-10-22 05:08 UTC, jganczorz-revolve commented on OsmIntegrator/AutoMapper/ConversationProfile.cs
> +      AllowNullCollections = true;
Nie wiem, kopiowałem poprzednie rozwiązania

2021-10-22 05:09 UTC, jganczorz-revolve commented on OsmIntegrator/Controllers/ConversationController.cs
> +    [HttpPut("Approve/{id}")]
Nie trzeba zmieniać frontu?
To jest akurat parametr w URLa, więc na froncie nie ma nazwy.
Więc pozmieniam tutaj na conversationId

2021-10-22 05:11 UTC, jganczorz-revolve commented on OsmIntegrator/ApiModels/Conversation.cs
> +  public class Conversation
Rozmawialiśmy o tym z Marcinem i dokładnie problemy z zarządzaniem dodatkowym statusem przeważały korzyści.

2021-10-22 05:12 UTC, jganczorz-revolve commented on OsmIntegrator/Controllers/ConversationController.cs
> +    public async Task<ActionResult> Reject(string id)
W pierwszej wersji diagramu przewidywaliśmy.
Zostawiam, najwyżej nikt nigdy tego nie użyje. A jak się zmieni koncepcja, to kod już jest.
To i tak tylko zmienia status ostatniej wiadomości na Reject

2021-10-22 05:13 UTC, jganczorz-revolve commented on OsmIntegrator/Controllers/ConversationController.cs
> +    public async Task<ActionResult> Approve([FromBody] MessageInput messageInput)
Redundantna
Obie są poprawne, tylko ta pierwsza nie pozwala na dodanie tekstu do zatwierdzenia.
Ale jako że była wcześniej taka możliwość z notatkami, to zostawiłem

2021-10-22 05:15 UTC, jganczorz-revolve commented on OsmIntegrator/ApiModels/Conversation.cs
> +    public double? Lat { get; set; }
Nie są wymagane
W metodzie muszę dodać sprawdzenie, ale wymagane jest lat+lon lub stopId

2021-10-22 05:54 UTC, jganczorz-revolve commented on OsmIntegrator/Controllers/ConversationController.cs
> +      ConversationResponse response = new ConversationResponse()
A w jaki sposób wyświetlisz pinezki/przystanki z raportami, nie mając tych informacji na froncie?

2021-10-22 21:06 UTC, luktar requested changes

2021-10-22 21:06 UTC, luktar commented on OsmIntegrator/ApiModels/Conversation.cs
> +    public Guid TileId { get; set; }
Kuba tutaj chodzi o dodanie `?` do Guid, bo walidator tego nie chwyci.

2021-10-22 21:06 UTC, luktar commented on OsmIntegrator/AutoMapper/ConversationProfile.cs
> +      AllowNullCollections = true;
https://docs.automapper.org/en/stable/Lists-and-arrays.html#handling-null-collections

Można to ustawić globalnie. Nie wiem, czy to jest konieczne. Jak myślisz?

2021-10-25 07:28 UTC, luktar approved these changes

2021-10-25 13:04 UTC, merged