Change current emails
technologiesforaccessibility/osmintegrator-backend pull request #77
Opened 2021-10-25 13:05 UTC by jganczorz-revolve

2021-10-25 21:30 UTC, luktar commented
Jeszcze brakuje tych wymagań:
```
<server>

server name: (not present on production)

osmintegrator.eu

osmintegrator-test.ovh

localhost

Email title

Add [TEST] or [LOCALHOST] to the title if an email comes from the test or localhost server.
```

2021-10-25 21:31 UTC, luktar requested changes

2021-10-25 21:31 UTC, luktar commented on OsmIntegrator/Controllers/AccountController.cs
>          // to do: create function to generate email message and subject
To nie jest już potrzebne.

2021-10-25 21:31 UTC, luktar commented on OsmIntegrator/Controllers/AccountController.cs
> +      message.Subject = _localizer["Resset password"];
W tytule brakuje zwrotu [TEST] albo [LOCAL] w zależności od tego, czy email wyszedł z serwera testowego lub localhost.
Localhost jest wtedy, gdy istnieje zmienna środowiskowa "ASPNETCORE_ENVIRONMENT": "Development", a test wtedy, gdy domena jest osmintegrator-test.ovh (nie wiem jak to można sprawdzić).

2021-10-26 14:05 UTC, luktar approved these changes
Dodałem komentarze

2021-10-26 14:05 UTC, luktar commented on OsmIntegrator/Controllers/TileController.cs
> +{_localizer["Regards"]},
Footer w sumie jest wszędzie taki sam. Title też.

2021-10-26 14:05 UTC, luktar commented on OsmIntegrator/Controllers/TileController.cs
> +      builder.TextBody = $@"{_localizer["Hello"]} {user.UserName},
Po co text i html body?

2021-10-27 12:14 UTC, jganczorz-revolve commented on OsmIntegrator/Controllers/TileController.cs
> +      builder.TextBody = $@"{_localizer["Hello"]} {user.UserName},
Text jest wyświetlany, jeżeli klient nie obsługuje html (albo screen readery itp)
Generalnie spam assasin źle patrzy na wiadomości z html, a bez text

2021-10-28 04:43 UTC, merged