Feature/pt 270
technologiesforaccessibility/osmintegrator-backend pull request #78
Opened 2021-10-27 09:04 UTC by jganczorz-revolve

2021-10-28 18:14 UTC, luktar requested changes
Jutro o tym pogadamy. Wielu rzeczy nie rozumiem.

2021-10-28 18:14 UTC, luktar commented on OsmIntegrator/Controllers/TileController.cs
> +        List<DbTile> editorTiles = await _dbContext.Tiles
Nie rozumiem co tu się dzieje. Wyjaśnimy to jutro na su.

2021-10-28 18:14 UTC, luktar commented on OsmIntegrator/Controllers/TileController.cs
> +    /// DEPRECATED
Nie ma co trzymać starych metod. Tu nie ma kompatybilności wstecznej.

2021-10-28 18:14 UTC, luktar commented on OsmIntegrator/Database/Models/DbTileUser.cs
> +    public ApplicationRole Role { get; set; }
Użytkownik może mieć wiele ról. Dlaczego ma jedną?

2021-10-29 05:53 UTC, jganczorz-revolve commented on OsmIntegrator/Controllers/TileController.cs
> +    /// DEPRECATED
Ale istnieje możliwość, że wypuścisz backend bez nowego frontu

2021-10-29 05:53 UTC, jganczorz-revolve commented on OsmIntegrator/Database/Models/DbTileUser.cs
> +    public ApplicationRole Role { get; set; }
To jest w zasadzie rozszerzona tabela do relacji ManyToMany User <-> Tile
Dla jednego kafelka użytkownik może być albo edytorem, albo supervisorem
Znaczy, mógłby być tutaj tym i tym (mieć dwa rekordy w tabeli), ale to akurat walidacja nie pozwoli

2021-11-03 20:46 UTC, luktar approved these changes

2021-11-03 20:46 UTC, merged